apiVersion: v1
kind: Service
metadata:
  name: transfer-service
  labels:
    app: transfer-service
spec:
  selector:
    app: transfer-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}