apiVersion: v1
kind: ConfigMap
metadata:
  name: user-auth-config
data:
  application.yml: |-
    server:
      port: {{ .Values.service.port }}
    spring:
      application:
        name: user-auth-service
      main:
        web-application-type: {{ .Values.config.spring.main.web_application_type }}
      webflux:
        static-path-pattern: {{ .Values.config.spring.webflux.static_path_pattern }}
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: "{{ .Values.config.spring.security.oauth2.resourceserver.jwt.issuer_uri }}"
              jwk-set-uri: "{{ .Values.config.spring.security.oauth2.resourceserver.jwt.jwk_set_uri }}"
          client:
            registration:
              account-service:
                provider: {{ .Values.config.spring.security.oauth2.client.registration.account_service.provider }}
                client-id: {{ .Values.config.spring.security.oauth2.client.registration.account_service.client_id }}
                client-authentication-method: {{ .Values.config.spring.security.oauth2.client.registration.account_service.client_authentication_method }}
                authorization-grant-type: {{ .Values.config.spring.security.oauth2.client.registration.account_service.authorization_grant_type }}
                scope: {{ toYaml .Values.config.spring.security.oauth2.client.registration.account_service.scope | nindent 16 }}
            provider:
              account-service:
                token-uri: {{ .Values.config.spring.security.oauth2.client.provider.account_service.token_uri }}
    jwt:
      secret: {{ .Values.config.jwt.secret | quote }}
      expiration: {{ .Values.config.jwt.expiration }}
      issuer: {{ .Values.config.jwt.issuer }}
    management:
      endpoints:
        web:
          exposure:
            include: {{ toYaml .Values.config.management.endpoints.web.exposure.include | nindent 14 }}
      endpoint:
        health:
          show_details: {{ .Values.config.management.endpoint.health.show_details }}
    logging:
      level:
        org.springframework: {{ .Values.config.logging.level.org_springframework }}
        ru.practicum: {{ .Values.config.logging.level.ru_practicum }}
        org.springframework.web: {{ .Values.config.logging.level.org_springframework_web }}
        org.springframework.cloud: {{ .Values.config.logging.level.org_springframework_cloud }}
        org.springframework.cloud.gateway: {{ .Values.config.logging.level.org_springframework_cloud_gateway }}
        reactor.netty: {{ .Values.config.logging.level.reactor_netty }}
        org.springframework.security: {{ .Values.config.logging.level.org_springframework_security }}
        org.springframework.cloud.consul: {{ .Values.config.logging.level.org_springframework_cloud_consul }}
      pattern:
        console: {{ .Values.config.logging.pattern.console | quote }}