apiVersion: v1
kind: ConfigMap
metadata:
  name: blocker-config
data:
  application.yml: |-
    server:
      port: {{ .Values.service.port }}
    spring:
      application:
        name: blocker-service
      profiles:
        active: {{ .Values.env.SPRING_PROFILES_ACTIVE }}
      main:
        web-application-type: reactive
    management:
      endpoints:
        web:
          exposure:
            include: {{ toYaml .Values.config.management.endpoints.web.exposure.include | nindent 14 }}
      endpoint:
        health:
          show_details: {{ .Values.config.management.endpoint.health.show_details }}
    logging:
      level:
        org.springframework: {{ .Values.config.logging.level.org_springframework }}
        ru.practicum: {{ .Values.config.logging.level.ru_practicum }}
        org.springframework.cloud.consul: {{ .Values.config.logging.level.org_springframework_cloud_consul }}
      pattern:
        console: {{ .Values.config.logging.pattern.console | quote }}