replicaCount: 1

image:
  repository: minikube.local/blocker-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8084

env:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_R2DBC_URL: r2dbc:postgresql://postgres-service:5432/blocker_service
  SPRING_R2DBC_USERNAME: postgres
  AUTH_SERVICE_JWT_ISSUER_URI: http://ingress-nginx-controller/serv-auth-service
  AUTH_SERVICE_JWK_SET_URI: http://ingress-nginx-controller/serv-auth-service/oauth2/jwks
  SPRING_R2DBC_POOL_ENABLED: "true"
  SPRING_R2DBC_POOL_INITIAL_SIZE: "10"
  SPRING_R2DBC_POOL_MAX_SIZE: "50"
  SPRING_R2DBC_POOL_MAX_IDLE_TIME: "30m"
  SPRING_R2DBC_POOL_MAX_LIFE_TIME: "60m"
  SPRING_R2DBC_POOL_VALIDATION_QUERY: "SELECT 1"

secrets:
  DB_PASSWORD: postgres

config:
  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics
    endpoint:
      health:
        show_details: always
  logging:
    level:
      org_springframework: INFO
      ru_practicum: DEBUG
      org_springframework_cloud_consul: INFO
    pattern:
      console: "%d{dd-MM-yyyy HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"