server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account-service/**
          filters:
            - StripPrefix=1
        - id: cash-service
          uri: lb://cash-service
          predicates:
            - Path=/cash-service/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics