server:
  port: 8081

spring:
  main:
    web-application-type: reactive
  application:
    name: front-ui-service
  logging:
    level:
      org.springframework: INFO
      org.springframework.security: INFO
      pattern:
        console: %d{dd-MM-yyyy HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n