apiVersion: v1
kind: Service
metadata:
  name: api-gateway-server
  labels:
    app: api-gateway-server
spec:
  selector:
    app: api-gateway-server
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}