apiVersion: v1
kind: ConfigMap
metadata:
  name: account-config
data:
  application.yml: |-
    server:
      port: {{ .Values.service.port }}
    app:
      currencies:
        supported: {{ toYaml .Values.config.app.currencies.supported | nindent 8 }}
    spring:
      application:
        name: account-service
      profiles:
        active: {{ .Values.env.SPRING_PROFILES_ACTIVE }}
      main:
        web-application-type: reactive
    management:
      endpoints:
        web:
          exposure:
            include: {{ toYaml .Values.config.management.endpoints.web.exposure.include | nindent 14 }}
      endpoint:
        health:
          show_details: {{ .Values.config.management.endpoint.health.show_details }}
    logging:
      level:
        org.springframework: {{ .Values.config.logging.level.org_springframework }}
        ru.practicum: {{ .Values.config.logging.level.ru_practicum }}
        org.springframework.web: {{ .Values.config.logging.level.org_springframework_web }}
        org.springframework.cloud: {{ .Values.config.logging.level.org_springframework_cloud }}
        org.springframework.cloud.gateway: {{ .Values.config.logging.level.org_springframework_cloud_gateway }}
        reactor.netty: {{ .Values.config.logging.level.reactor_netty }}
        org.springframework.security: {{ .Values.config.logging.level.org_springframework_security }}
      pattern:
        console: {{ .Values.config.logging.pattern.console | quote }}