global:
  imagePullPolicy: IfNotPresent
  db:
    password: postgres

postgres:
  enabled: true
  primary:
    persistence:
      enabled: true
      size: 8Gi
  secret:
    POSTGRES_PASSWORD: postgres

serv-auth-service:
  enabled: true
  replicaCount: 1
  image:
    repository: serv-auth-service
    tag: latest
  service:
    port: 9000
  secret:
    DB_PASSWORD: postgres

user-auth-service:
  enabled: true
  replicaCount: 1
  image:
    repository: user-auth-service
    tag: latest
  service:
    port: 8083

account-service:
  enabled: true
  replicaCount: 1
  image:
    repository: account-service
    tag: latest
  service:
    port: 8082

blocker-service:
  enabled: false
  replicaCount: 1
  image:
    repository: blocker-service
    tag: latest
  service:
    port: 8084

cash-service:
  enabled: false
  replicaCount: 1
  image:
    repository: cash-service
    tag: latest
  service:
    port: 8085

exchange-service:
  enabled: true
  replicaCount: 1
  image:
    repository: exchange-service
    tag: latest
  service:
    port: 8086

exchange-generator-service:
  enabled: true
  replicaCount: 1
  image:
    repository: exchange-generator-service
    tag: latest
  service:
    port: 8087

notification-service:
  enabled: false
  replicaCount: 1
  image:
    repository: notification-service
    tag: latest
  service:
    port: 8089

transfer-service:
  enabled: false
  replicaCount: 1
  image:
    repository: transfer-service
    tag: latest
  service:
    port: 8088

nginx-gateway:
  enabled: true

front-ui-service:
  enabled: true
  replicaCount: 1
  image:
    repository: front-ui-service
    tag: latest
  service:
    port: 8081

kafka:
  enabled: true
  replicaCount: 2
  image:
    registry: docker.io
    repository: bitnamilegacy/kafka
    tag: "4.0.0-debian-12-r10"
    pullPolicy: Never
  auth:
    interBrokerProtocol: "plaintext"
  listeners:
    client:
      protocol: "PLAINTEXT"
  kraft:
    enabled: true
  provisioning:
    enabled: true
    topics:
      - name: exchange-rates
        partitions: 3
        replicationFactor: 1
        config:
          cleanup.policy: delete
          retention.ms: 86400000  # 1 день
          min.insync.replicas: 1
      - name: notification
        partitions: 3
        replicationFactor: 1
        config:
          cleanup.policy: delete
          retention.ms: 86400000  # 1 день
          min.insync.replicas: 1
  persistence:
    enabled: true
    size: 1Gi

zipkin:
  enabled: true
  replicaCount: 1
  image:
    repository: openzipkin/zipkin-slim
    tag: "2.24.1"
    pullPolicy: IfNotPresent

prometheus:
  enabled: true
  server:
    service:
      type: ClusterIP
      servicePort: 9090
  extraScrapeConfigs: |
    - job_name: 'account-service'
      metrics_path: /actuator/prometheus
      static_configs:
        - targets: [ 'account-service.{{ .Release.Namespace }}.svc.cluster.local:8082' ]
          labels:
            application: 'account-service'
    - job_name: 'blocker-service'
      metrics_path: /actuator/prometheus
      static_configs:
        - targets: [ 'blocker-service.{{ .Release.Namespace }}.svc.cluster.local:8084' ]
          labels:
            application: 'blocker-service'
    - job_name: 'cash-service'
      metrics_path: /actuator/prometheus
      static_configs:
        - targets: [ 'cash-service.{{ .Release.Namespace }}.svc.cluster.local:8085' ]
          labels:
            application: 'cash-service'
    - job_name: 'exchange-generator-service'
      metrics_path: /actuator/prometheus
      static_configs:
        - targets: [ 'exchange-generator-service.{{ .Release.Namespace }}.svc.cluster.local:8087' ]
          labels:
            application: 'exchange-generator-service'
    - job_name: 'exchange-service'
      metrics_path: /actuator/prometheus
      static_configs:
        - targets: [ 'exchange-service.{{ .Release.Namespace }}.svc.cluster.local:8086' ]
          labels:
            application: 'exchange-service'
    - job_name: 'notification-service'
      metrics_path: /actuator/prometheus
      static_configs:
        - targets: [ 'notification-service.{{ .Release.Namespace }}.svc.cluster.local:8089' ]
          labels:
            application: 'notification-service'
    - job_name: 'serv-auth-service'
      metrics_path: /actuator/prometheus
      static_configs:
        - targets: [ 'serv-auth-service.{{ .Release.Namespace }}.svc.cluster.local:9000' ]
          labels:
            application: 'serv-auth-service'
    - job_name: 'transfer-service'
      metrics_path: /actuator/prometheus
      static_configs:
        - targets: [ 'transfer-service.{{ .Release.Namespace }}.svc.cluster.local:8088' ]
          labels:
            application: 'transfer-service'
    - job_name: 'user-auth-service'
      metrics_path: /actuator/prometheus
      static_configs:
        - targets: [ 'user-auth-service.{{ .Release.Namespace }}.svc.cluster.local:8083' ]
          labels:
            application: 'user-auth-service'
    - job_name: 'front-ui-service'
      metrics_path: /actuator/prometheus
      static_configs:
        - targets: [ 'front-ui-service.{{ .Release.Namespace }}.svc.cluster.local:8081' ]
          labels:
            application: 'front-ui-service'
  serverFiles:
    alerting_rules.yml:
      groups:
        - name: http_errors
          rules:
            - alert: HighHttp5xxErrorRate
              expr: >
                sum(rate(http_server_requests_seconds_count{status=~"5.."}[1m])) 
                / 
                sum(rate(http_server_requests_seconds_count[1m])) 
                > 0.1
              for: 2m
              labels:
                severity: warning
              annotations:
                summary: "Высокий процент 5xx ошибок"
        - name: login_failures
          rules:
            - alert: HighLoginFailureRate
              expr: |
                sum by (login) (increase(login_fail_count_total[5m])) > 5
              for: 1m
              labels:
                severity: critical
              annotations:
                summary: "Неудачные логины"
                description: "{{ $labels.login }}: более 5 неудачных логинов за 5 минут"
        - name: blocked_operation
          rules:
            - alert: SuspiciousTransferBlocked
              expr: | 
                increase(blocked_operation_count_total[1m]) > 0
              for: 0m
              labels:
                severity: warning
              annotations:
                summary: "Заблокирована операция"
                description: "{{ $labels.account }}: заблокирована операция"

grafana:
  enabled: true
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000
  adminUser: admin
  adminPassword: admin
  ingress:
    enabled: false
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: 'http://microbank-prometheus-server.{{ .Release.Namespace }}.svc.cluster.local:9090'
          isDefault: true
  extraVolumeMounts:
    - name: custom-dashboards
      mountPath: /var/lib/grafana/dashboards/custom
      readOnly: false
  extraVolumes:
    - name: custom-dashboards
      configMap:
        name: grafana-dashboards
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
        - name: custom
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/custom
  dashboards:
    default:
      spring-boot:
        gnetId: 10280
        revision: 1
        datasource: Prometheus
      jvm-overview:
        gnetId: 4701
        revision: 2
        datasource: Prometheus
  persistence:
    enabled: true
    size: 1Gi