pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = credentials('DOCKER_REGISTRY')
        DB_PASSWORD     = credentials('DB_PASSWORD')
        GITHUB_USERNAME = credentials('GITHUB_USERNAME')
        DB_NAME         = 'postgres'
        DB_USER         = 'postgres'
        IMAGE_TAG       = "latest"
    }

    stages {
        stage('Build & Unit Tests') {
            parallel {
                stage('serv-auth-service') {
                    steps {
                        dir('serv-auth-service') {
                            sh 'mvn clean test'
                        }
                    }
                }
                stage('user-auth-service') {
                    steps {
                        dir('user-auth-service') {
                            sh 'mvn clean test'
                        }
                    }
                }
                stage('front-ui-service') {
                    steps {
                        dir('front-ui-service') {
                            sh 'mvn clean test'
                        }
                    }
                }
                stage('account-service') {
                    steps {
                        dir('account-service') {
                            sh 'mvn clean test'
                        }
                    }
                }
                stage('exchange-service') {
                    steps {
                        dir('exchange-service') {
                            sh 'mvn clean test'
                        }
                    }
                }
                stage('exchange-generator-service') {
                    steps {
                        dir('exchange-generator-service') {
                            sh 'mvn clean test'
                        }
                    }
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                sh """
                docker build -t serv-auth-service:${IMAGE_TAG} -f serv-auth-service/Dockerfile .
                docker build -t user-auth-service:${IMAGE_TAG} -f user-auth-service/Dockerfile .
                docker build -t front-ui-service:${IMAGE_TAG} -f front-ui-service/Dockerfile .
                docker build -t account-service:${IMAGE_TAG} -f account-service/Dockerfile .
                docker build -t exchange-service:${IMAGE_TAG} -f exchange-service/Dockerfile .
                docker build -t exchange-generator-service:${IMAGE_TAG} -f exchange-generator-service/Dockerfile .
                """
            }
        }

        stage('Push Docker Images') {
            steps {
                withCredentials([string(credentialsId: 'GHCR_TOKEN', variable: 'GHCR_TOKEN')]) {
                    sh """
                    echo \$GHCR_TOKEN | docker login ghcr.io -u ${GITHUB_USERNAME} --password-stdin
                    """
                }
            }
        }

        stage('Install PostgreSQL to TEST') {
            steps {
                sh """
                helm upgrade --install postgres umbrella-chart/charts/postgres \\
                  --namespace test --create-namespace \\
                  --set auth.database=${DB_NAME} \\
                  --set auth.username=${DB_USER} \\
                  --set auth.password=${DB_PASSWORD}
                """
            }
        }

        stage('Deploy Kafka (KRaft) to test') {
            steps {
                dir('umbrella-chart') {
                    sh 'helm dependency build'

                    sh """
                    helm upgrade --install microbank . \\
                      --set kafka.enabled=true \\
                      --set kafka.kraft.enabled=true \\
                      --set kafka.controller.replicaCount=3 \\
                      --set postgres.enabled=false \\
                      --set serv-auth-service.enabled=false \\
                      --set user-auth-service.enabled=false \\
                      --set account-service.enabled=false \\
                      --set blocker-service.enabled=false \\
                      --set cash-service.enabled=false \\
                      --set exchange-service.enabled=false \\
                      --set exchange-generator-service.enabled=false \\
                      --set notification-service.enabled=false \\
                      --set transfer-service.enabled=false \\
                      --set nginx-gateway.enabled=false \\
                      --set front-ui-service.enabled=false \\
                      --namespace test --create-namespace
                    """
                }
            }
        }

        stage('Create DB Secrets for TEST') {
            steps {
                sh """
                kubectl create secret generic postgres \\
                  --from-literal=password=${DB_PASSWORD} \\
                  -n test --dry-run=client -o yaml | kubectl apply -f -
                """
            }
        }

        stage('Helm Deploy to TEST') {
            steps {
                sh """
                helm upgrade --install serv-auth-service umbrella-chart/charts/serv-auth-service \\
                  --namespace test --create-namespace \\
                  --set image.repository=serv-auth-service \\
                  --set image.tag=${IMAGE_TAG} \\
                  --set ingress.enabled=true \\
                  --set ingress.hosts[0].host=auth.test.local \\
                  --set ingress.hosts[0].paths[0].path="/" \\
                  --set ingress.hosts[0].paths[0].pathType="ImplementationSpecific"

                helm upgrade --install user-auth-service umbrella-chart/charts/user-auth-service \\
                  --namespace test --create-namespace \\
                  --set image.repository=user-auth-service \\
                  --set image.tag=${IMAGE_TAG} \\
                  --set ingress.enabled=true \\
                  --set ingress.hosts[0].host=user-auth.test.local \\
                  --set ingress.hosts[0].paths[0].path="/" \\
                  --set ingress.hosts[0].paths[0].pathType="ImplementationSpecific"

                helm upgrade --install nginx-gateway umbrella-chart/charts/nginx-gateway \\
                  --namespace test --create-namespace \\
                  --set service.internal.enabled=true

                helm upgrade --install front-ui-service umbrella-chart/charts/front-ui-service \\
                  --namespace test --create-namespace \\
                  --set image.repository=front-ui-service \\
                  --set image.tag=${IMAGE_TAG} \\
                  --set ingress.enabled=true \\
                  --set ingress.hosts[0].host=front.test.local \\
                  --set ingress.hosts[0].paths[0].path="/" \\
                  --set ingress.hosts[0].paths[0].pathType="ImplementationSpecific"

                helm upgrade --install account-service umbrella-chart/charts/account-service \\
                  --namespace test --create-namespace \\
                  --set image.repository=account-service \\
                  --set image.tag=${IMAGE_TAG} \\
                  --set ingress.enabled=true \\
                  --set ingress.hosts[0].host=account.test.local \\
                  --set ingress.hosts[0].paths[0].path="/" \\
                  --set ingress.hosts[0].paths[0].pathType="ImplementationSpecific"

                helm upgrade --install exchange-service umbrella-chart/charts/exchange-service \\
                  --namespace test --create-namespace \\
                  --set image.repository=exchange-service \\
                  --set image.tag=${IMAGE_TAG} \\
                  --set ingress.enabled=true \\
                  --set ingress.hosts[0].host=exchange.test.local \\
                  --set ingress.hosts[0].paths[0].path="/" \\
                  --set ingress.hosts[0].paths[0].pathType="ImplementationSpecific"

                helm upgrade --install exchange-generator-service umbrella-chart/charts/exchange-generator-service \\
                  --namespace test --create-namespace \\
                  --set image.repository=exchange-generator-service \\
                  --set image.tag=${IMAGE_TAG} \\
                  --set ingress.enabled=true \\
                  --set ingress.hosts[0].host=exchange-generator.test.local \\
                  --set ingress.hosts[0].paths[0].path="/" \\
                  --set ingress.hosts[0].paths[0].pathType="ImplementationSpecific"
                """
            }
        }

        stage('Manual Approval for PROD') {
            steps {
                input message: 'Deploy to PROD environment?', ok: 'Yes, deploy'
            }
        }

        stage('Install PostgreSQL to PROD') {
            steps {
                sh """
                helm upgrade --install postgres umbrella-chart/charts/postgres \\
                  --namespace prod --create-namespace \\
                  --set auth.database=${DB_NAME} \\
                  --set auth.username=${DB_USER} \\
                  --set auth.password=${DB_PASSWORD}
                """
            }
        }

        stage('Deploy Kafka (KRaft) to prod') {
            steps {
                dir('umbrella-chart') {
                    sh 'helm dependency build'

                    sh """
                    helm upgrade --install microbank . \\
                      --set kafka.enabled=true \\
                      --set kafka.kraft.enabled=true \\
                      --set kafka.controller.replicaCount=3 \\
                      --set postgres.enabled=false \\
                      --set serv-auth-service.enabled=false \\
                      --set user-auth-service.enabled=false \\
                      --set account-service.enabled=false \\
                      --set blocker-service.enabled=false \\
                      --set cash-service.enabled=false \\
                      --set exchange-service.enabled=false \\
                      --set exchange-generator-service.enabled=false \\
                      --set notification-service.enabled=false \\
                      --set transfer-service.enabled=false \\
                      --set nginx-gateway.enabled=false \\
                      --set front-ui-service.enabled=false \\
                      --namespace prod --create-namespace
                    """
                }
            }
        }

        stage('Create DB Secrets for PROD') {
            steps {
                sh """
                kubectl create secret generic postgres \\
                  --from-literal=password=${DB_PASSWORD} \\
                  -n prod --dry-run=client -o yaml | kubectl apply -f -
                """
            }
        }
        
        stage('Helm Deploy to PROD') {
            steps {
                sh """
                helm upgrade --install serv-auth-service umbrella-chart/charts/serv-auth-service \\
                  --namespace prod --create-namespace \\
                  --set image.repository=serv-auth-service \\
                  --set image.tag=${IMAGE_TAG} \\
                  --set ingress.enabled=true \\
                  --set ingress.hosts[0].host=auth.prod.local \\
                  --set ingress.hosts[0].paths[0].path="/" \\
                  --set ingress.hosts[0].paths[0].pathType="ImplementationSpecific"

                helm upgrade --install user-auth-service umbrella-chart/charts/user-auth-service \\
                  --namespace prod --create-namespace \\
                  --set image.repository=user-auth-service \\
                  --set image.tag=${IMAGE_TAG} \\
                  --set ingress.enabled=true \\
                  --set ingress.hosts[0].host=user-auth.prod.local \\
                  --set ingress.hosts[0].paths[0].path="/" \\
                  --set ingress.hosts[0].paths[0].pathType="ImplementationSpecific"

                helm upgrade --install nginx-gateway umbrella-chart/charts/nginx-gateway \\
                  --namespace prod --create-namespace \\
                  --set service.internal.enabled=true

                helm upgrade --install front-ui-service umbrella-chart/charts/front-ui-service \\
                  --namespace prod --create-namespace \\
                  --set image.repository=front-ui-service \\
                  --set image.tag=${IMAGE_TAG} \\
                  --set ingress.enabled=true \\
                  --set ingress.hosts[0].host=front.prod.local \\
                  --set ingress.hosts[0].paths[0].path="/" \\
                  --set ingress.hosts[0].paths[0].pathType="ImplementationSpecific"

                helm upgrade --install account-service umbrella-chart/charts/account-service \\
                  --namespace prod --create-namespace \\
                  --set image.repository=account-service \\
                  --set image.tag=${IMAGE_TAG} \\
                  --set ingress.enabled=true \\
                  --set ingress.hosts[0].host=account.prod.local \\
                  --set ingress.hosts[0].paths[0].path="/" \\
                  --set ingress.hosts[0].paths[0].pathType="ImplementationSpecific"

                helm upgrade --install exchange-service umbrella-chart/charts/exchange-service \\
                  --namespace prod --create-namespace \\
                  --set image.repository=exchange-service \\
                  --set image.tag=${IMAGE_TAG} \\
                  --set ingress.enabled=true \\
                  --set ingress.hosts[0].host=exchange.prod.local \\
                  --set ingress.hosts[0].paths[0].path="/" \\
                  --set ingress.hosts[0].paths[0].pathType="ImplementationSpecific"

                helm upgrade --install exchange-generator-service umbrella-chart/charts/exchange-generator-service \\
                  --namespace prod --create-namespace \\
                  --set image.repository=exchange-generator-service \\
                  --set image.tag=${IMAGE_TAG} \\
                  --set ingress.enabled=true \\
                  --set ingress.hosts[0].host=exchange-generator.prod.local \\
                  --set ingress.hosts[0].paths[0].path="/" \\
                  --set ingress.hosts[0].paths[0].pathType="ImplementationSpecific"
                """
            }
        }
    }
}