server:
  port: 8888

spring:
  cloud:
    config:
      server:
        consul:
          host: localhost
          port: 8500
          prefix: config
          default-context: application
          format: YAML
          data-key: data

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, configprops
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.config: DEBUG