apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
data:
  application.yml: |-
    server:
      port: {{ .Values.service.port }}
    spring:
      application:
        name: notification-service
      profiles:
        active: {{ .Values.env.SPRING_PROFILES_ACTIVE }}
      mail:
        host: {{ .Values.config.spring.mail.host }}
        port: {{ .Values.config.spring.mail.port }}
        properties:
          mail:
            smtp:
              auth: {{ .Values.config.spring.mail.properties.mail.smtp.auth }}
              starttls:
                enable: {{ .Values.config.spring.mail.properties.mail.smtp.starttls.enable }}
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: "{{ .Values.env.AUTH_SERVICE_JWT_ISSUER_URI }}"
              jwk-set-uri: "{{ .Values.env.AUTH_SERVICE_JWK_SET_URI }}"
    management:
      endpoints:
        web:
          exposure:
            include: {{ toYaml .Values.config.management.endpoints.web.exposure.include | nindent 14 }}
      endpoint:
        health:
          show_details: {{ .Values.config.management.endpoint.health.show_details }}
    logging:
      level:
        org.springframework: {{ .Values.config.logging.level.org_springframework }}
        ru.practicum: {{ .Values.config.logging.level.ru_practicum }}
        org.springframework.cloud.consul: {{ .Values.config.logging.level.org_springframework_cloud_consul }}
      pattern:
        console: {{ .Values.config.logging.pattern.console | quote }}