apiVersion: v1
kind: ConfigMap
metadata:
  name: exchange-generator-config
data:
  application.yml: |-
    server:
      port: {{ .Values.service.port }}
    exchange:
      rate:
        generation:
          interval:
            ms: {{ .Values.config.exchange.rate.generation.interval.ms }}
    app:
      currencies:
        supported: {{ toYaml .Values.config.app.currencies.supported | nindent 8 }}
    spring:
      application:
        name: exchange-generator-service
      scheduling:
        enabled: {{ .Values.config.spring.scheduling.enabled }}
      task:
        scheduling:
          enabled: {{ .Values.config.spring.task.scheduling.enabled }}
      main:
        web-application-type: reactive
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: "{{ .Values.env.AUTH_SERVICE_JWT_ISSUER_URI }}"
              jwk-set-uri: "{{ .Values.env.AUTH_SERVICE_JWK_SET_URI }}"
          client:
            registration:
              exchange-service:
                provider: {{ .Values.config.security.oauth2.client.registration.exchange_service.provider }}
                client-id: {{ .Values.config.security.oauth2.client.registration.exchange_service.client_id }}
                client-authentication-method: {{ .Values.config.security.oauth2.client.registration.exchange_service.client_authentication_method }}
                authorization-grant-type: {{ .Values.config.security.oauth2.client.registration.exchange_service.authorization_grant_type }}
                scope: {{ toYaml .Values.config.security.oauth2.client.registration.exchange_service.scope | nindent 16 }}
            provider:
              exchange-service:
                token-uri: {{ .Values.config.security.oauth2.client.provider.exchange_service.token_uri }}
    management:
      endpoints:
        web:
          exposure:
            include: {{ toYaml .Values.config.management.endpoints.web.exposure.include | nindent 14 }}
      endpoint:
        health:
          show_details: {{ .Values.config.management.endpoint.health.show_details }}
    logging:
      level:
        org.springframework: {{ .Values.config.logging.level.org_springframework }}
        ru.practicum: {{ .Values.config.logging.level.ru_practicum }}
        org.springframework.cloud.consul: {{ .Values.config.logging.level.org_springframework_cloud_consul }}
      pattern:
        console: {{ .Values.config.logging.pattern.console | quote }}