apiVersion: v1
kind: Service
metadata:
  name: exchange-generator-service
  labels:
    app: exchange-generator-service
spec:
  selector:
    app: exchange-generator-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}